# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

fos_ck_editor:
    configs:
        main_config:
            toolbar:
                - {
                    name: "styles",
                    items: [
                        "Bold",
                        "Italic",
                        "Underline",
                        "Strike",  
                        "Blockquote",
                        "-",
                        "RemoveFormat",
                        "-",
                        "NumberedList",
                        "BulletedList",
                        "-",
                        "Outdent",
                        "Indent",  
                        "-",
                        "-",
                        "JustifyLeft",
                        "JustifyRight",
                        "JustifyCenter",
                        "JustifyBlock",
                        "-",
                        "Image",
                        "Table",
                        "-",
                        "Styles",
                        "Format",
                        "Font",
                        "FontSize",
                        "-",
                        "TextColor",
                        "BGColor",
                        "Source",
                    ],
                  }
